### ISSUE TITLE
Handle network issues

### ISSUE THREAD

**Issue by puzanov** [maddevsio/new-para-bot#1]
```
bot_1  | 2018/03/31 00:10:39 Get https://api.binance.com/api/v1/exchangeInfo: read tcp 172.19.0.2:56460->52.85.184.209:443: read: connection reset by peer
bot_1  | panic: Get https://api.binance.com/api/v1/exchangeInfo: read tcp 172.19.0.2:56460->52.85.184.209:443: read: connection reset by peer
bot_1  | 
bot_1  | goroutine 1 [running]:
bot_1  | log.Panic(0xc4204b9f00, 0x1, 0x1)
bot_1  | 	/usr/local/go/src/log/log.go:326 +0xc0
bot_1  | main.checkBinanceAndAlert()
bot_1  | 	/src/github.com/maddevsio/new-para-bot/main/main.go:30 +0x10c
bot_1  | main.main()
bot_1  | 	/src/github.com/maddevsio/new-para-bot/main/main.go:15 +0x66
```

**Comment by puzanov** [comment]
Not actual. Docker restart policy solves this issue.
